/* empty css                      */import{a as v,S as b,i as w}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=n(e);fetch(e.href,a)}})();const S="49461257-d92cdcbbc0ac75fcae3d36a6d",q="https://pixabay.com/api/";async function d(t,r){const{data:n}=await v(q,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return n}const u=document.querySelector(".loader"),f=document.querySelector(".load-more-button"),M=new b(".gallery a",{captionsData:"alt"});function m(t,r){const n=t.map(o=>`
    <a class="gallery-item" href="${o.largeImageURL}">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      <div class="info">
        <p><span>Likes:</span> ${o.likes}</p>
        <p><span>Views:</span> ${o.views}</p>
        <p><span>Comments:</span> ${o.comments}</p>
        <p><span>Downloads:</span> ${o.downloads}</p>
      </div>
    </a>
  `).join("");r.insertAdjacentHTML("beforeend",n),M.refresh()}function P(t){t.innerHTML=""}function s(t){w.error({title:"Error",message:t})}function p(){u.classList.remove("visually-hidden")}function y(){u.classList.add("visually-hidden")}function g(){f.classList.remove("visually-hidden")}function h(){f.classList.add("visually-hidden")}const $=document.querySelector(".form"),i=document.querySelector(".gallery"),B=document.querySelector(".load-more-button");$.addEventListener("submit",E);B.addEventListener("click",A);let c=1,L=null;async function E(t){t.preventDefault(),h(),P(i);const r=t.target.elements["search-text"].value.trim();if(L=r,!r){s("You forgot important data");return}c=1,p();try{const{hits:n,totalHits:o}=await d(r,c);n.length||s("Sorry, there are no images matching your search query. Please try again!"),m(n,i),i.querySelectorAll("a").length<o&&g()}catch{s("Failed to load images. Please try again!")}finally{y()}}async function A(){h(),p(),c+=1;try{const{hits:t,totalHits:r}=await d(L,c);m(t,i),i.querySelectorAll("a").length<r?g():s("We're sorry, but you've reached the end of search results.");const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"})}catch{s("Failed to load images. Please try again!")}finally{y()}}
//# sourceMappingURL=index.js.map
